### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [suzuyu0115/meshitelog#113]
@suzuyu0115 
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

```
1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

## READMEから課題解決する実装がされているか&動いている
飯テロの要素が組み込まれており機能もしっかり実装されています。
時間指定しての投稿や対象ユーザーの選択など面白いアプリですね！

## 静的コードチェックが入っている
rubocop導入してチェック内容も定義してコードチェックしてますね！引き続きrubocop使っていきましょう！

## 就活において十分な技術力を示せる機能を実装しているか
LIFFの導入やsidekiqでのバッチ処理などサービスをよくするために技術を盛り込めていますね。まtRailsの機能もしっかり把握した上でコードが実装されています。
追加で、飯テロしているユーザーの投稿内容などを分析したアルゴリズムなどを用いて、似たような投稿があった場合に勝手にオススメされるなどがあるとさらに技術アピールになるので時間と相談しつつ追加実装の参考にしてみてください。
### レコメンド
投稿されたまたは事前に用意されたコンテンツと類似したコンテンツを推奨する機能をレコメンドと呼びます。代表的なアルゴリズムとして、協調フィルタリングとコンテンツフィルタリングがあります。協調フィルタリングは、ユーザの行動や嗜好データを元に類似度を算出し、コンテンツベースフィルタリングは、コンテンツの数値化された特徴や評価を元に類似度を算出します。

### 使用技術・ライブラリ
* Amazon Personalize
    * https://docs.aws.amazon.com/ja_jp/personalize/latest/dg/what-is-personalize.html
    * AWSが提供する機械学習の知識がなくても、個々のユーザー向けにリコメンデーションをリアルタイムで提供できるサービスです。
* GCP Recommendations AI
    * https://cloud.google.com/recommendations?hl=ja
    * Recommendations AIは、Google Cloud Platformが提供するレコメンドエンジンであり、Googleの機械学習アルゴリズムを利用しています。
* アルゴリズム
    * 協調フィルタリングやコンテンツベースフィルタリングは、一般的にアルゴリズムが公開されているので、RubyやPythonで独自に実装することも可能です。

### 気になった点
また下記に気になった箇所をあげているのでご確認ください。

- post.rbのpost_urlメソッドなどでURLが固定になっている部分は定数で定義してあげましょう。（ROOT_URL = ...）
- posts_controllerのshowアクションの条件分岐はmodelに処理を切り出してあげましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
LIFFベースでとても使いやすいですね、使い方もLINEから確認できるので初心者でも利用しやすいかなと思います！
下記に気になった点を挙げるのでご確認ください。

- 投稿する際の送り相手の選択をするときに毎回チェックを入れてやるのが億劫になるかもしれないので、デフォルトの送り先があるといいかもです！（チェックがない場合は全員に送る、ランダムの10人に送るなど）
- 投稿一覧を見る際に、検索フォームがあるのはいいですが、どんなタグがあるのかが把握できないので、人気のあるタグなどタグのジャンルを表示してそこから検索できるようにしてあげましょう。
- 投稿一覧で新着順で出ているかと思いますが、他のデータでも並び順を変更できるようにするといいですね（いいね順など）
- 複数タグを登録する際に、全角コンマであることを少し強調して表示してあげてもいいですね。
- ページネーションにtruncateの文字列が出ちゃっているので修正しておきましょう。
- 一覧ページからいいねするとcontent missingのエラーが出る時があるので修正しておきましょう。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by suzuyu0115** [comment]
@kerochelo 
かんのさん、レビューいただきありがとうございます！
また、アプリも使っていただいて大変嬉しいです！ありがとうございます🙇‍♂️

リリース日につきましては8月末までの本リリースを予定しております。
何卒よろしくお願いいたします。

**Comment by kerochelo** [comment]
@suzuyu0115 
OKっす、引き続き頑張っていきましょう！
